name: rcsb-embedding-search
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=openblas
  - brotli-python=1.0.9=py311h313beb8_7
  - bzip2=1.0.8=h80987f9_5
  - ca-certificates=2024.2.2=hf0a4a13_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - filelock=3.13.1=py311hca03da5_0
  - freetype=2.12.1=h1192e45_0
  - fsspec=2024.3.1=pyhca7485f_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py311h40f64dc_0
  - idna=3.4=py311hca03da5_0
  - jinja2=3.1.3=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - lightning=2.2.2=pyhd8ed1ab_0
  - lightning-utilities=0.11.2=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.3=py311h80987f9_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.1=py311hca03da5_0
  - numpy=1.26.4=py311he598dae_0
  - numpy-base=1.26.4=py311hfbfe69c_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.2.1=h0d3ecfb_1
  - packaging=24.0=pyhd8ed1ab_0
  - pillow=10.2.0=py311h80987f9_0
  - pip=23.3.1=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.8=hb885b13_0
  - pytorch=2.2.2=py3.11_0
  - pytorch-lightning=2.2.2=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h80987f9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=py311hca03da5_1
  - setuptools=68.2.2=py311hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - sympy=1.12=py311hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - torchaudio=2.2.2=py311_cpu
  - torchmetrics=1.3.2=pyhd8ed1ab_0
  - torchvision=0.17.2=py311_cpu
  - tqdm=4.66.2=pyhd8ed1ab_0
  - typing-extensions=4.9.0=py311hca03da5_1
  - typing_extensions=4.9.0=py311hca03da5_1
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.1.0=py311hca03da5_1
  - wheel=0.41.2=py311hca03da5_0
  - xz=5.4.6=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
  - pip:
    - torcheval==0.0.7
